sources:
  - type: snowflake
    details:
      account: ${SNOWFLAKE_ACCOUNT}
      user: ${SNOWFLAKE_USER}
      password: ${SNOWFLAKE_PASSWORD}
      warehouse: 'demo'
      database: 'demo_db'
      schema: 'public'
      role: 'accountadmin'